musicRecommendation/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),

    path("",views.index_view,name="index"),
    
    path("play/",include("play.urls")),
    path("user/",include("user.urls")),
    path("recommend/",include("recommend.urls")),
]

play/urls.py
from django.urls import path

from . import views
app_name='play'

urlpatterns = [
    path('detail/', views.detail_view,name='detail'), 
    path('rating/', views.rating,name='rating'),
    path('comment/', views.comment,name='comment'),
]

recommend/urls.py
from django.urls import path

from . import views
app_name='recommend'

urlpatterns = [
    path('recommendation/', views.recommendation_view,name='recommendation'),
]

play/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# 歌曲分类表
class Label(models.Model):
    label_id = models.AutoField('序号', primary_key=True)
    label_name = models.CharField('分类标签', max_length=10)

    def __str__(self):
        return self.label_name

    class Meta:
        verbose_name = '歌曲分类'
        verbose_name_plural = '歌曲分类'


# 歌曲信息表
class Song(models.Model):
    song_id = models.AutoField('序号', primary_key=True)
    song_name = models.CharField('歌名', max_length=50)
    song_time = models.CharField('时长', max_length=10)
    song_album = models.CharField('专辑', max_length=50)
    song_languages = models.CharField('语种', max_length=20)
    song_release = models.DateField('发行时间', max_length=20)
    song_img = models.CharField('歌曲图片', max_length=100)
    song_lyrics = models.CharField('歌词', max_length=500, default='暂无歌词')
    song_file = models.CharField('歌曲文件', max_length=100)
    label = models.ForeignKey(Label, on_delete=models.CASCADE,verbose_name='类型')
    singer = models.ManyToManyField(User, verbose_name='歌手') #多对多

    def __str__(self):
        return self.song_name

    class Meta:
        verbose_name = '歌曲信息'
        verbose_name_plural = '歌曲信息'


# 歌曲动态表
class Dynamic(models.Model):
    dynamic_id = models.AutoField('序号', primary_key=True)
    song = models.ForeignKey(Song, on_delete=models.CASCADE, verbose_name='歌名')
    dynamic_plays = models.IntegerField('播放次数')
    dynamic_search = models.IntegerField('搜索次数')
    dynamic_down = models.IntegerField('下载次数')

    class Meta:
        verbose_name = '歌曲动态'
        verbose_name_plural = '歌曲动态'


# 歌曲评论表
class Comment(models.Model):
    comment_id = models.AutoField('序号', primary_key=True)
    comment_text = models.CharField('内容', max_length=500)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    song = models.ForeignKey(Song, on_delete=models.CASCADE, verbose_name='歌名')
    comment_date = models.DateField('日期', max_length=50)

    class Meta:
        verbose_name = '歌曲评论'
        verbose_name_plural = '歌曲评论'


# 歌曲评分表
class Rating(models.Model):
    rating_id = models.AutoField('序号', primary_key=True)
    rating_number = models.IntegerField('评分')
    rating_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    song = models.ForeignKey(Song, on_delete=models.CASCADE, verbose_name='歌名')
    rating_date = models.DateField('日期', max_length=50)

    class Meta:
        verbose_name = '歌曲评分'
        verbose_name_plural = '歌曲评分'

recommend/models.py
from django.db import models

# Create your models here.

play/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from datetime import date

# Create your views here.

@login_required(login_url='user:login')
def detail_view(request):
    song_id=request.GET.get('id')
    #将song_id存入seesion,后续评分和评论需要用到
    request.session["song_id"]=song_id #写入session(也写入浏览器cookie中)
    #获取歌曲详情
    songInfo=Song.objects.get(song_id=song_id) 
    #print('songInfo',songInfo)
    #获取对应的歌手信息（可能有多个歌手）
    singers=songInfo.singer.all()
    #print('singers',singers)
    #获取评论信息
    current_song = Song.objects.get(pk=request.session.get('song_id'))
    current_user = User.objects.get(username=request.session.get('info'))
    comments=Comment.objects.filter(song=current_song).order_by('-comment_date')
    return render(request,'play/detail.html',{"songInfo":songInfo,'singers':singers,'comments':comments})

def rating(request):
    if request.method == 'GET':
        current_song = Song.objects.get(pk=request.session.get('song_id'))
        current_user = User.objects.get(username=request.session.get('info'))
        rating=Rating.objects.filter(song=current_song,rating_user=current_user)
        if(len(rating)==0):
            rating_number=0
        else:
            rating_number=rating[0].rating_number
        return JsonResponse({"msg": "查询成功", "rating_number":rating_number,"success": True})
    if request.method == 'POST':
        current_song = Song.objects.get(pk=request.session.get('song_id'))
        current_user = User.objects.get(username=request.session.get('info'))
        rating_number =request.POST.get("rating_number")
        Rating.objects.update_or_create(
            song=current_song,
            rating_user=current_user,
            defaults={'rating_number': rating_number,'rating_date':date.today()}
        )
        return JsonResponse({"msg": "评分成功", "success": True})
        
def comment(request):
    current_song = Song.objects.get(pk=request.session.get('song_id'))
    current_user = User.objects.get(username=request.session.get('info'))
    comment_text =request.POST.get("comment_text")
    Comment.objects.create(
            song=current_song,
            comment_user=current_user,
            comment_text=comment_text,
            comment_date=date.today()
        )
    return JsonResponse({"msg": "评论发布成功", "success": True})

recommend/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
#数据分析
import numpy as np
import pandas as pd
import math
import random
#分页
from django.core.paginator import Paginator , PageNotAnInteger,EmptyPage

from play.models import *

# Create your views here.
@login_required(login_url='user:login')
def recommendation_view(request):

    ratings=Rating.objects.all()

    #数据准备
    users=dict()
    all_items=set()
    for rating in ratings:
        all_items.add(rating.song.song_name)
        if(rating.rating_user.username in users.keys()):
            users[rating.rating_user.username][rating.song.song_name]=rating.rating_number
        else:
            users[rating.rating_user.username]=dict()
            users[rating.rating_user.username][rating.song.song_name]=rating.rating_number
    ##print(users)

    ##print('当前用户',request.session.get('info'))

    current_user=request.session.get('info')
    rated_items=set([key for key in users[current_user].keys() if users[current_user][key] > 0])
    unrated_items=list(all_items.__sub__(rated_items))
    ##print(unrated_items)

    #基于用户相似度的协同过滤推荐
    userCF_result=userCF(users,unrated_items,current_user)
    FM_BiasSVD_result=FM_BiasSVD(users,unrated_items,current_user)
    ##print('基于用户相似度的协同过滤推荐结果'，userCF_result)
    ##print('基于矩阵分解的协同过滤推荐结果',FM_BiasSVD_result)

    userCF_songs=Song.objects.filter(song_name__in=list(userCF_result))
    FM_BiasSVD_songs=Song.objects.filter(song_name__in=list(FM_BiasSVD_result))

    # print('userCF_songs',userCF_songs)
    # print('FM_BiasSVD_songs',FM_BiasSVD_songs)

    #分页
    userCF_paginator = Paginator(userCF_songs,6)
    try:
    # GET请求方式，get()获取指定Key值所对应的value值
    # 获取index的值，如果没有，则设置使用默认值1
        userCF_number = request.GET.get('userCF_number','1')
    # 获取第几页
        userCF_page = userCF_paginator.page(userCF_number)
    except PageNotAnInteger:
    # 如果输入的页码数不是整数，那么显示第一页数据
        userCF_page = userCF_paginator.page(1)
    except EmptyPage:
        userCF_page = userCF_paginator.page(userCF_paginator.num_pages)

    FM_BiasSVD_paginator = Paginator(FM_BiasSVD_songs,6)
    try:
    # GET请求方式，get()获取指定Key值所对应的value值
    # 获取index的值，如果没有，则设置使用默认值1
        FM_BiasSVD_number = request.GET.get('FM_BiasSVD_number','1')
    # 获取第几页
        FM_BiasSVD_page = FM_BiasSVD_paginator.page(FM_BiasSVD_number)
    except PageNotAnInteger:
    # 如果输入的页码数不是整数，那么显示第一页数据
        FM_BiasSVD_page = FM_BiasSVD_paginator.page(1)
    except EmptyPage:
        FM_BiasSVD_page = FM_BiasSVD_paginator.page(FM_BiasSVD_paginator.num_pages)
    

    return render(request,'play/recommend.html',{'userCF_page':userCF_page,'userCF_paginator':userCF_paginator,'FM_BiasSVD_page':FM_BiasSVD_page,'FM_BiasSVD_paginator':FM_BiasSVD_paginator})

#基于用户相似度的协同过滤推荐
def userCF(users,unrated_items,current_user):
    user_data = users
    ##用户相似度矩阵
    similarity_matrix = pd.DataFrame(
        np.identity(len(user_data)),
        index=user_data.keys(),
        columns=user_data.keys(),)
    for u in user_data.keys():
        for v in user_data.keys():
            if u == v:
                continue
            u_set = set( [key for key in user_data[u].keys() if user_data[u][key] > 0])
            v_set = set( [key for key in user_data[v].keys() if user_data[v][key] > 0])
            similarity_matrix[u][v] = float(len(u_set & v_set)) / math.sqrt(len(u_set) * len(v_set))
    ###print('*************相似度矩阵*****************')
    ###print(similarity_matrix)
    ##当前登录的用户
    target_user = current_user
    num = 2
    # 由于最相似的用户为自己，去除本身
    sim_users = similarity_matrix[target_user].sort_values(ascending=False)[1:num+1].index.tolist()
    ##预测当前用户对未评分的item的评分
    target_item_list = unrated_items
    target_rating_list = []
    for target_item in target_item_list:
        weighted_scores = 0.
        weighted_sum = 0.
        for user in sim_users:
            u_set=set( [key for key in user_data[user].keys() if user_data[user][key] > 0])
            if(target_item not in u_set):
                user_data[user][target_item]=0
            weighted_scores += similarity_matrix[target_user][user] * user_data[user][target_item] 
            weighted_sum += similarity_matrix[target_user][user]
        target_item_pred = weighted_scores / weighted_sum
        target_rating_list.append(target_item_pred)
    ###print('*************预测评分*****************')
    ###print(target_rating_list)
    ##将结果降序排序，并返回
    sorted_target_rating_list, sorted_target_item_list = zip(*sorted(zip(target_rating_list, target_item_list),reverse=True))
    return sorted_target_item_list

#基于矩阵分解的协同过滤推荐

class BiasSVD():
    def __init__(self, rating_data, F=5, alpha=0.1, lmbda=0.1, max_iter=100):
        self.F = F          # 这个表示隐向量的维度
        self.P = dict()     # 用户矩阵P  大小是[users_num, F]
        self.Q = dict()     # 物品矩阵Q  大小是[item_nums, F]
        self.bu = dict()    # 用户偏置系数
        self.bi = dict()    # 物品偏置系数
        self.mu = 0         # 全局偏置系数
        self.alpha = alpha  # 学习率
        self.lmbda = lmbda  # 正则项系数
        self.max_iter = max_iter        # 最大迭代次数
        self.rating_data = rating_data  # 评分矩阵

        for user, items in self.rating_data.items():
            # 初始化矩阵P和Q, 随机数需要和1/sqrt(F)成正比
            self.P[user] = [random.random() / math.sqrt(self.F) for x in range(0, F)]
            self.bu[user] = 0
            for item, rating in items.items():
                if item not in self.Q:
                    self.Q[item] = [random.random() / math.sqrt(self.F) for x in range(0, F)]
                    self.bi[item] = 0

    # 采用随机梯度下降的方式训练模型参数
    def train(self):
        cnt, mu_sum = 0, 0
        for user, items in self.rating_data.items():
            for item, rui in items.items():
                mu_sum, cnt = mu_sum + rui, cnt + 1
        self.mu = mu_sum / cnt

        for step in range(self.max_iter):
            # 遍历所有的用户及历史交互物品
            for user, items in self.rating_data.items():
                # 遍历历史交互物品
                for item, rui in items.items():
                    rhat_ui = self.predict(user, item)  # 评分预测
                    e_ui = rui - rhat_ui  				# 评分预测偏差

                    # 参数更新
                    self.bu[user] += self.alpha * (e_ui - self.lmbda * self.bu[user])
                    self.bi[item] += self.alpha * (e_ui - self.lmbda * self.bi[item])
                    for k in range(0, self.F):
                        self.P[user][k] += self.alpha * (e_ui * self.Q[item][k] - self.lmbda * self.P[user][k])
                        self.Q[item][k] += self.alpha * (e_ui * self.P[user][k] - self.lmbda * self.Q[item][k])
            # 逐步降低学习率
            self.alpha *= 0.1


    # 评分预测
    def predict(self, user, item):
        return sum(self.P[user][f] * self.Q[item][f] for f in range(0, self.F)) + self.bu[user] + self.bi[item] + self.mu
    

def FM_BiasSVD(users,unrated_items,current_user):
    rating_data = users
    # 建立模型
    basicsvd = BiasSVD(rating_data, F=3)
    # 参数训练
    basicsvd.train()
    # 预测用户对item的评分
    target_item_list = unrated_items
    target_rating_list = []
    for item in target_item_list:
        target_rating_list.append(basicsvd.predict(current_user, item))
    
    ##将结果降序排序，并返回
    sorted_target_rating_list, sorted_target_item_list = zip(*sorted(zip(target_rating_list, target_item_list),reverse=True))
    return sorted_target_item_list

templates/play/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>歌曲详情页</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="{%static 'css/songdetail.css'%}">
    <link rel="stylesheet" href="{%static 'css/rating.css'%}">

</head>

<body>

    {% comment %} 音频播放 {% endcomment %}
    

    <div class="container">
        <div class="row">
            <div class="col-sm-4 p-3">
                <div class="song-cover">
                    <img src="{%static '/songImg/' %}{{songInfo.song_img}}">
                </div>
            </div>
            <div class="col-sm-8 p-3">
                <div class="song-info">
                    <h2>{{songInfo.song_name}}</h2>
                    <div class="singer-box">
                        <img src="{% static 'image/个人头像.png' %}">
                        {%for singer in singers%}
                        <span>{{singer.username}}</span>
                        {% endfor %}
                    </div>
                    <div class="text">流派：{{songInfo.label}}</div>
                    <div class="text">语种：{{songInfo.song_languages}}</div>
                    <div class="text">发行时间：{{songInfo.song_release}}</div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-4 p-3">
                    <audio controls>
                        <source src="{%static 'songFile/孤勇者.m4a'%}" type="audio/mpeg">
                    </audio>
                </div>
                <div class="col-sm-4 p-3">
                    {#评分#}
                    <ul id="rating" class="rating">
                        <li class="rating-item rating" title="很不好"></li>
                        <li class="rating-item rating" title="不好"></li>
                        <li class="rating-item rating" title="一般"></li>
                        <li class="rating-item rating" title="好"></li>
                        <li class="rating-item rating" title="很好"></li>
                    </ul>
                    <ul id="titleText"></ul> {#文本描述#}
                </div>
            </div>
        </div>
        {#评论#}
        <div class="row">
            <div class="panel panel-info">
                <div class="panel-body">
                    <form class="bs-example bs-example-form" role="form" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="input-group">
                                    <input id="comment_text" type="text" class="form-control">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button" onclick="comment()">
                                           发布评论
                                        </button>
                                    </span>
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                        </div><!-- /.row -->
                    </form>
                </div>
            </div>
        </div>

        <div class="row">
            {%for comment in comments%}
            <div class="panel panel-info"> 
                <div class="panel-body">
                {{comment.comment_text}}{{comment.comment_date}}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


    <script>

        function comment() {
            $.ajax({
                url: "{% url 'play:comment' %}",
                type: "post",
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    "comment_text": $("#comment_text").val(),
                },
                success: function (e) {
                    alert("评论发布成功")
                },
    
            })
    
        }
    // 点亮方法
    var rating = (function(){
        var lightOn = function($item,num){
            $item.each(function(index){
                if(index<num){
                    $(this).removeClass('rating-item').addClass('rating-itemYellow')
                }else{
                    $(this).addClass('rating-item').removeClass('rating-itemYellow')
                }
            });
        }
        var init= function(el,num){
            var titleText = "";
            var $rating = $(el),
            $item = $rating.find('.rating');
            // 初始化
            lightOn($item,num);
            // 鼠标移入事件，点击事件，鼠标移出事件
            $rating.on('mouseover','.rating',function(){
                lightOn($item,$(this).index()+1);
                var titleText = $(this).attr('title')
                $('#titleText').text(titleText)
            }).on('click','.rating',function(){
                num = $(this).index()+1;
                titleText = $(this).attr('title')
                $('#titleText').text(titleText) //点击星号后显示对应的文本 

                //修改评分
                $.ajax({
                    url: "{% url 'play:rating' %}",
                    type: "post",
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        "rating_number": num,
                    },
                    success: function (e) {
                        console.log(e)
                        alert("评分修改成功")
                    },
                })

            }).on('mouseout',function(){
                lightOn($item,num);
                $('#titleText').text(titleText)
            });

        };
        $.fn.extend({
            rating:function(num){
                return this.each(function(){
                    init(this,num);
                });
            }
        });
        // 返回一个对象
        return {
            init:init
        };
    })();

    // 获取当前用户对歌曲的评分,调用点亮方法
    $(document).ready(function(){
        $.ajax({
            url: "{% url 'play:rating' %}",
            type: "get",
            success: function (e) {
                console.log('rating_number',e.rating_number)
                // 初始化星号
                rating.init('#rating',e.rating_number);
            },
        })
    });

    
    </script>

</body>

</html>

templates/play/recommend.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">  
<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{% static 'css/recommend.css' %}">
{% endblock head %}

{% block content %}
<div class="container">
    <h3>基于用户相似度的协同过滤推荐</h3>
</div>

{#基于用户相似度的推荐音乐列表#}
<div class="container">
    <div class="row">
        {% for song in userCF_page.object_list %}
        <div class="col-sm-2 p-3">
            <a class="songlink" href="{%url 'play:detail'%}?id={{song.song_id}}">
                <div class="song-item">
                    <img src="{%static '/songImg/' %}{{song.song_img}}">
                    <div class="text">{{song.song_name}} </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{#分页效果#}
<div class="text-center">
<ul class="pagination">
    {# 如果当前页还有上一页 #}
    {% if userCF_page.has_previous %}
    <li>
        <a href="{%url 'recommend:recommendation'%}?userCF_number={{userCF_page.previous_page_number}}">上一页</a>
    </li>
    {% else %}
    {# 如果没有上一页， 则上一页按钮不可点击 #}
    <li class="disabled">
        <a href="#">上一页</a>
    </li>
    {% endif %}

    {% for page_number in userCF_paginator.page_range %}
        {# 获取当前页的页码 #}
        {% if page_number == userCF_page.number %}
        {# 如果是当前页的话，选中 #}
        <li class="active">
            <a href="{%url 'recommend:recommendation'%}?userCF_number={{page_number}}">{{page_number}}</a>
        </li>
        {% else %}
        <li>
            <a href="{%url 'recommend:recommendation'%}?userCF_number={{page_number}}">{{page_number}}</a>
        </li>
        {% endif %}
    {% endfor %}

    {% if userCF_page.has_next %}
    <li>
        <a href="{%url 'recommend:recommendation'%}?userCF_number={{userCF_page.next_page_number}}">下一页</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="#">下一页</a>
    </li>
    {% endif %}
</ul>
</div>


<div class="container">
    <h3>基于矩阵分解的协同过滤推荐</h3>
</div>

{#基于用户相似度的推荐音乐列表#}
<div class="container">
    <div class="row">
        {% for song in FM_BiasSVD_page.object_list %}
        <div class="col-sm-2 p-3">
            <a class="songlink" href="{%url 'play:detail'%}?id={{song.song_id}}">
                <div class="song-item">
                    <img src="{%static '/songImg/' %}{{song.song_img}}">
                    <div class="text">{{song.song_name}} </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{#分页效果#}
<div class="text-center">
<ul class="pagination">
    {# 如果当前页还有上一页 #}
    {% if FM_BiasSVD_page.has_previous %}
    <li>
        <a href="{%url 'recommend:recommendation'%}?FM_BiasSVD_number={{FM_BiasSVD_page.previous_page_number}}">上一页</a>
    </li>
    {% else %}
    {# 如果没有上一页， 则上一页按钮不可点击 #}
    <li class="disabled">
        <a href="#">上一页</a>
    </li>
    {% endif %}

    {% for page_number in FM_BiasSVD_paginator.page_range %}
        {# 获取当前页的页码 #}
        {% if page_number == FM_BiasSVD_page.number %}
        {# 如果是当前页的话，选中 #}
        <li class="active">
            <a href="{%url 'recommend:recommendation'%}?FM_BiasSVD_number={{page_number}}">{{page_number}}</a>
        </li>
        {% else %}
        <li>
            <a href="{%url 'recommend:recommendation'%}?FM_BiasSVD_number={{page_number}}">{{page_number}}</a>
        </li>
        {% endif %}
    {% endfor %}

    {% if FM_BiasSVD_page.has_next %}
    <li>
        <a href="{%url 'recommend:recommendation'%}?FM_BiasSVD_number={{FM_BiasSVD_page.next_page_number}}">下一页</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="#">下一页</a>
    </li>
    {% endif %}
</ul>
</div>
{% endblock %}