musicRecommendation/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),

    path("",views.index_view,name="index"),
    
    path("play/",include("play.urls")),
    path("user/",include("user.urls")),
    path("recommend/",include("recommend.urls")),
]

play/urls.py
from django.urls import path

from . import views
app_name='play'

urlpatterns = [
    path('detail/', views.detail_view,name='detail'), 
    path('rating/', views.rating,name='rating'),
    path('comment/', views.comment,name='comment'),
]

recommend/urls.py
from django.urls import path

from . import views
app_name='recommend'

urlpatterns = [
    path('recommendation/', views.recommendation_view,name='recommendation'),
]

user/urls.py
from django.urls import path

from . import views
app_name='user'

urlpatterns = [
    path('login/',views.LoginView.as_view(),name="login"),
    path('logout/',views.to_logout, name="logout"),

    path('analysis/',views.analysis,name='analysis')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<%=basePath%>">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>音乐推荐系统</title>


    <!--CDN引入Bootstrap-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 新 Bootstrap5 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <!-- 最新的 Bootstrap5 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <style>
        :root {
            --green: #31c27c;
            --gray: #aba9a9;
            --lightblue: rgb(104, 163, 194);
        }
    </style>
    {% block head %}{% endblock head %}
</head>
<body>
    <div class="container-fluid" style="padding: 0;">
        <!-- 头部导航栏 -->
    <div id="header">
        <div class="name">
            <span>音乐推荐系统</span>
        </div>
        <div class="top_nav">
            <ul>
                <li>
                    <a href="{% url 'index' %}">首页</a>
                </li>
                <li>
                    <a href="{% url 'recommend:recommendation' %}">推荐</a>
                </li>

                {% comment %} 歌手才看查看数据分析页面 {% endcomment %}
                {% if request.session.group == "singer" %}
                <li>
                    <a href="{% url 'user:analysis' %}">数据分析</a>
                </li>
                {% else %}
                {% endif %}

                {% if request.session.group == None %}
                <li>
                    <a href="{% url 'user:login' %}">登录</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'user:logout' %}">退出登录</a>
                </li>
                {% endif %}

            </ul>
        </div>
        {% comment %} <div class="user">
            <img src="http://thirdqq.qlogo.cn/g?b=sdk&k=jyVBpozdpqW3elFGreDHMw&kti=Y_YHEwAAAAE&s=140&t=1677060465">
        </div> {% endcomment %}
    </div>

    </div>


    {%block content%}{% endblock%}


    <div id="footer">个性化音乐推荐系统</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
{% endblock head %}

{% block content %}

    <!-- 内容 -->

    <!-- 搜索 -->
    <div class="container">
        <div class="search-box">
            <input class="search-txt" type='text' id='search_input' placeholder="搜索" />
            <!-- <input class="search-btn" type='button' id='search_btn'/> -->
            <img class="search-btn" src="{%static 'image/search.jpg'%}" id='search_btn'>
        </div>
    </div>
    <!-- 轮播图＋月度榜单列表 -->
    <div class="container">
        <div class="row">
            <div class="col-sm-8 p-3">
                <div id="demo" class="carousel slide" data-bs-ride="carousel">

                    <!-- 指示符 -->
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                        <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
                        <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
                    </div>

                    <!-- 轮播图片 -->
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="https://y.qq.com/music/common/upload/MUSIC_FOCUS/4573989.jpg?max_age=2592000"
                                class="d-block" style="width:100%">
                        </div>
                        <div class="carousel-item">
                            <img src="https://y.qq.com/music/common/upload/MUSIC_FOCUS/4573620.png?max_age=2592000"
                                class="d-block" style="width:100%">
                        </div>
                        <div class="carousel-item">
                            <img src="https://y.qq.com/music/common/upload/MUSIC_FOCUS/4574093.jpg?max_age=2592000"
                                class="d-block" style="width:100%">
                        </div>
                    </div>

                    <!-- 左右切换按钮 -->
                    <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon"></span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                        <span class="carousel-control-next-icon"></span>
                    </button>
                </div>
            </div>
            <div class="col-sm-4 p-3">
                <div style="font-size: 20px;text-align: center;background-color:beige;color: darkgreen;">榜单</div>
                <ul class="list-group">
                    {% for song in monthlyTopSongList %}
                    <li style='list-style: none;font-size: 16px; text-align: left;margin: 2px 15px;'>
                        <a class="songlink" href="{%url 'play:detail'%}?id={{song.song_id}}">{{song.song_name}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <!-- 今日热门 -->
    <div class="container">
        <div class="row" >
            <div class="col-sm-3 p-3">
                <div class="rec-icon">
                    <img src="{%static 'image/recommend.png'%}">
                    <div style="font-size: 30px;color:#fff;">今日热点</div>
                </div>
            </div>
            {% for song in dailyTopSongList %}
            <div class="col-sm-3 p-3">
                <a class="songlink" href="{%url 'play:detail'%}?id={{song.song_id}}">
                    <div class="rec-item">
                        <img src="{%static '/songImg/' %}{{song.song_img}}" alt="封面" style="float: left;">
                        <div class="item-box">
                            <div class="name">{{song.song_name}}</div>
                            <div class="singer">{{song.song_singer}}</div>
                            <div class="date">发行时间：{{song.song_release}}</div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        <hr />
    </div>


{% endblock content %}